#!/bin/sh

# To kill autorun, create `.killscript' in the same
# directory as autorun; note that autorun removes
# any such .killscript as it commits suicide.
# To pause autorun, create `pause' in the same
# directory as autorun.  autorun will pause for 40
# seconds before checking to see if the pause file
# has been removed---autorun will continue to pause
# until the pause file is manually removed.

PORT="1024"
FLAGS=""
UPTIME_FILE=log/lastdeath

while [ 1 ];
do
  DATE=`date`
#  echo "autorun: Starting game $DATE" >> syslog

  # This is probably no longer needed..
#  ulimit -c unlimited

  # If there's a levgen directory, then build the
  # maze.  Using `cd' is certainly not the safest
  # way to do this.  We should definitely move to
  # pushd/popd
#  if [ -d levgen ]; then
#    cd levgen
#    ./makmaz > mazelog
#    cd ..
#  fi

  # Run the game.
  bin/ageland $FLAGS $PORT #>> syslog 2>&1

  # Brief backoff before restarting, so a fast crash-loop doesn't
  # immediately re-trigger the full boot-time world-load memory spike
  # back-to-back with zero cooldown.
  sleep 5

  # Make our daily player/object/exploit file backups.
#  rm lib/backups/daily/players.tar
#  rm lib/backups/daily/plrobjs.tar
#  rm lib/backups/daily/exploits.tar
#  tar cf lib/backups/daily/players.tar lib/players
#  tar cf lib/backups/daily/plrobjs.tar lib/plrobjs
#  tar cf lib/backups/daily/exploits.tar lib/exploits

  # Populate our specialized logs with data from
  # the last run's syslog.
#  fgrep		"STATS"			syslog >> log/stats
#  fgrep		"self-delete"		syslog >> log/delete
#  fgrep		"auto-delete"		syslog >> log/delete
#  fgrep		"death trap"		syslog >> log/dts
#  fgrep		"killed"		syslog >> log/rip
#  fgrep		"Running"		syslog >> log/restarts
#  fgrep		"advanced"		syslog >> log/levels
#  fgrep		"equipment lost" 	syslog >> log/rentgone
#  fgrep		"usage"			syslog >> log/usage
#  fgrep		"new player"		syslog >> log/newchars
#  fgrep		"SYSERR"		syslog >> log/errors
#  fgrep		"(GC)"			syslog >> log/godcmds
#  fgrep		"Bad PW"		syslog >> log/badpws
#  fgrep		"] has connected"	syslog >> log/connect
#  fgrep         "Losing player:"        syslog >> log/disconnect
#  fgrep		"OBJ:" 			syslog >> log/object
#  fgrep         "namechanged:"          syslog >> log/namechanges

#  tail -4 lib/last_cmds >> syslog
#  tail -16 syslog > $UPTIME_FILE
#  more $UPTIME_FILE >> crashes

  # This is for crash monitoring on systems that
  # create core files in the form of core.<pid>.
  # This is mainly useful under the current version
  # of RedHat Linux and should be changed if run on
  # a different OS!
#  CORE=lib/ageland.core  # Updated for FreeBSD
#  if [ -f $CORE ]; then
#      NEWCORE=core/core-`date "+%Y-%m-%d-%H:%M:%S"`
#      BT_SCRIPT=lib/gdb_backtrace
#      echo >> $UPTIME_FILE
#      echo "***** GDB BACKTRACE *****" >> $UPTIME_FILE
#      gdb bin/ageland -c $CORE -x $BT_SCRIPT -batch -nx -tty=/dev/null >> $UPTIME_FILE
#      mv $CORE $NEWCORE
#      gzip $NEWCORE
#      echo >> $UPTIME_FILE
#      echo "Core file compressed and archived as $NEWCORE.gz" >> $UPTIME_FILE
#  fi
#  rm .ageland.pid

  # We keep 6 syslogs in store at any given time.
  # This increments our current store.
#  rm log/syslog.1
#  mv log/syslog.2 log/syslog.1
#  mv log/syslog.3 log/syslog.2
#  mv log/syslog.4 log/syslog.3
#  mv log/syslog.5 log/syslog.4
#  mv log/syslog.6 log/syslog.5
#  mv syslog       log/syslog.6
#  chmod g+rw log/*
#  touch syslog
#  chmod g+rw syslog

  # If .killscript exists, remove .killscript and exit
  if [ -r .killscript ]; then
    DATE=`date`
    echo "autorun: Killed by .killscript: $DATE" >> syslog
    rm -f .killscript
    exit
  fi

  # If a pause file exists, pause for 40 seconds
  while [ -r pause ];
  do
    echo "autorun: Pausing for 40 seconds: $DATE" >> syslog
    sleep 40
  done
done
